openapi: 3.0.0
info: 
  title: SAMPLE API EXPRESS
  version: 1.0.0
  host: localhost
  basePath: /api/v1
  termsOfService: 'https://github.com/brunohafonso95/sample-express-node/blob/master/README.md'
  contact:
    email: brunohafonso@gmail.com
  license:
    name: No license
  schemes:
    - http
  tags:
    - name: Users
      description: REST API that allows you to do a scaffolding
  servers:
    - url: /api/v1
components:
  schemas:
    User:
      properties:
        name:
          type: string
      required:
        - name
    CommonError:
      properties:
        message:
          type: string
      required:
        - message