openapi: 3.0.0
info: 
  title: SAMPLE API EXPRESS
  version: 1.0.0
  host: localhost
  basePath: /api/v1
  schemes:
    - http
components:
  schemas:
    User:
      properties:
        name:
          type: string
      required:
        - name
    CommonError:
      properties:
        message:
          type: string
      required:
        - message